### ISSUE TITLE
Missing dockerhub repository

### ISSUE THREAD

**Issue by graillus** [tuenti/secrets-manager#36]
I am trying to deploy the secret-manager to my k8s cluster, but I can't find the official repository on dockerhub (or is it [tuentitech/secrets-manager](https://hub.docker.com/r/tuentitech/secrets-manager) ? looks like it's empty)
The lack of a public docker repository is quite unexpected for an OS project designed to run on Kubernetes !

Is the dockerhub integration planned ?

How can I help ?

**Comment by fcgravalos** [comment]
Hi @graillus !! Thanks for using secrets-manager 
I agree with you, it's on the scope and I'll try to have it published as soon as possible

**Comment by dannyk81** [comment]
In the meantime, you can easily build your own docker image using the provided Dockerfile.

https://github.com/tuenti/secrets-manager/blob/master/Dockerfile

**Comment by smark88** [comment]
Till a public docker image is available the readme should state you need to build your own image and point at it in the deployment yaml.

**Comment by mward29** [comment]
I agree with smark88. It was annoying finding out after I had all the config setup that I now had to build the image.

**Comment by smark88** [comment]
> I agree with smark88. It was annoying finding out after I had all the config setup that I now had to build the image.

My helm chart has a built image in it if you need one. https://github.com/broadinstitute/datarepo-helm/tree/master/charts/install-secrets-manager
