### ISSUE TITLE
Missing return provokes wrong metrics delivery

### ISSUE THREAD

**Issue by eduardogr** [tuenti/secrets-manager#47]
We missed a return statement after the line 156 of the backend/vault.go file: 
* https://github.com/tuenti/secrets-manager/blob/master/backend/vault.go#L156

and this is provoking that we are sending successful login metrics when we shouldn't:

`c.logger.Info("login successful, got a new vault token")`

**Comment by dannyk81** [comment]
yes, indeed :sweat_smile: @fcgravalos actually caught that last week when we had a sealed Vault.

We'll do a quick PR to fix this, thanks for noticing this too :+1:

**Comment by eduardogr** [comment]
i've just created the issue because he told me about that, i'm uploading a quick fix, as soon as i upload it i create the PR
