### ISSUE TITLE
Vault crd comparison

### ISSUE THREAD

**Issue by jeroenrinzema** [tuenti/secrets-manager#53]
A comparison with `vault-crd` is made inside the README. I just wanted to point out that `vault-crd` is supporting KV1 and KV2. Maybe it is a good idea to rephrase the comparison to include the support of KV2 in `vault-crd`.

**Comment by fcgravalos** [comment]
Makes sense to me. This was right when I wrote the README, I guess we should update features comparison

**Comment by fcgravalos** [comment]
@jeroenrinzema if you have a suggestion, feel free to PR ;)
