### ISSUE TITLE
Add support for secret type of docker-registry

### ISSUE THREAD

**Issue by markAcomm** [tuenti/secrets-manager#68]
Thank you for making this tool... it has been an incredibly helpful piece of the puzzle in keeping secrets out of our git repositories.  While it is used heavily by our application developers, our DevOps engineers could use a little love on the k8s setup and management. 

Specifically, we will register the credentials of a private registry in all new app namesapces created so that engineers can [deploy images from a private registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).  It would be helpful if this daemon would support the Secret type of docker-registry along with the mechanics for registering private registry credentials sourced from Vault.  It looks like your CRD has already exposed the Secrets type, but your documentation suggests you only support `kubernetes.io/tls` and `Opaque`.

**Comment by phidlipus** [comment]
It would be be great if you could add support for `kubernetes.io/dockerconfigjson` secret type.

**Comment by rvojcik** [comment]
+1 for me :) it would be great. We have to sometimes rotate robot account secrets, it would be greate to just replace them in vault

**Comment by fcrespofastly** [comment]
Indeed it's supported. `secrets-manager` does not make any enforcement on the secret type.

**Comment by fcrespofastly** [comment]
@eduardogr we should close this issue.

**Comment by dkulchinsky** [comment]
indeed any supported type can be used, the README should be updated though, it does seem to suggest that only Opaque and TLS are supported.

**Comment by eduardogr** [comment]
i'll update the README with that information. 
Thanks @fcgravalos @dkulchinsky
