### ISSUE TITLE
new release v1.0.3 

### ISSUE THREAD

**Issue by fcrespofastly** [tuenti/secrets-manager#75]
Hey @eduardogr !

I wonder if it would make sense to bump to `v1.0.3`, now that we added the kubernetes auth functionality.

wdyt??

**Comment by eduardogr** [comment]
Since we decided to use semantic versioning, I bumped to `v1.1.0`
* release: https://github.com/tuenti/secrets-manager/releases/tag/v1.1.0
* docker image: https://hub.docker.com/r/tuentitech/secrets-manager/tags?page=1&ordering=last_updated

**Comment by eduardogr** [comment]
If you need something more let me know.

Thanks for your patient and your help @fcgravalos

**Comment by fcrespofastly** [comment]
Thank you!!
