### ISSUE TITLE
Secrets deletion proposal

### ISSUE THREAD

**Issue by fllaca** [tuenti/secrets-manager#8]
Proposal and implementation for a DELETE secret operation. It could be desirable that if a secret is removed from Vault, it is removed also from the K8s cluster which is referencing it.

Some posible behaviours:
- Delete in Vault => Delete on K8s and fail if the configmap is not updated
- Delete in Vault => Delete section in Configmap and delete the secret in K8s
- Delete in Vault => Just fail until the configmap is updated with the secret removed
- Delete in Configmap => Just do nothing as we do

Anything else?

**Comment by fcgravalos** [comment]
Closing as it's fixed by #30
